version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mock-xero-api

  frontend:
    build: ./frontend
    ports:
      - "4000:80" 
    depends_on:
      - backend

  mock-xero-api:
    image: jaypeng2015/show-me-the-money
    ports:
      - "3000:3000"